### ISSUE TITLE
Virtual Port 1 does not appear on get_iscsi_port() 

### ISSUE THREAD

**Issue by yossiovadia** [emc-openstack/storops#171]
naviseccli shows both Virtual Port ID 0 and 1 : 
`
/opt/Navisphere/bin/naviseccli -h 192.168.112.xx -user xxxx -password xxxx -scope global -np connection -getport -all

SP:  B
Port ID:  13
Port WWN:  iqn.1992-04.com.emc:cx.ckm00162000357.b13
iSCSI Alias:  357.b13
Enode MAC Address:  00-60-16-7A-15-AF
Port Speed:  10000 Mb
Auto-Negotiate:  No
Available Speeds:  10000 Mb
Current MTU:  9000
Available MTU Sizes:  "1260","1448","1500","1548","2000","2450","3000","4000","4080","4470","5000","6000","7000","8000","9000"
Flow Control:  Auto
Host Window:  256K
Replication Window:  256K
Available Window Sizes:  64K,128K,256K,512K,1MB

**Virtual Port ID:  0**
VLAN ID:  506
IP Address:  172.19.1.8
Subnet Mask:  255.255.255.0
Gateway Address:  0.0.0.0
Initiator Authentication:  false

**Virtual Port ID:  1**
VLAN ID:  358
IP Address:  172.17.3.224
Subnet Mask:  255.255.255.0
Gateway Address:  0.0.0.0
Initiator Authentication:  false

SP:  A
Port ID:  13
Port WWN:  iqn.1992-04.com.emc:cx.ckm00162000357.a13
iSCSI Alias:  357.a13
Enode MAC Address:  00-60-16-7A-19-1D
Port Speed:  10000 Mb
Auto-Negotiate:  No
Available Speeds:  10000 Mb
Current MTU:  9000
Available MTU Sizes:  "1260","1448","1500","1548","2000","2450","3000","4000","4080","4470","5000","6000","7000","8000","9000"
Flow Control:  Auto
Host Window:  256K
Replication Window:  256K
Available Window Sizes:  64K,128K,256K,512K,1MB

*Virtual Port ID:  0*
VLAN ID:  506
IP Address:  172.19.1.2
Subnet Mask:  255.255.255.0
Gateway Address:  0.0.0.0
Initiator Authentication:  false

*Virtual Port ID:  1*
VLAN ID:  358
IP Address:  172.17.3.222
Subnet Mask:  255.255.255.0
Gateway Address:  0.0.0.0
Initiator Authentication:  false

`

While  get_iscsi_port returns only port 0:

In [16]: vnx.get_iscsi_port(port_id=13)                                                                                                                                                                                          [3/1922]
Out[16]:
{
    "VNXConnectionPortList": [
        {
            "VNXConnectionPort": {
                "auto_negotiate": false,
                "current_mtu": 9000,
                "enode_mac_address": "00-60-16-7A-19-1D",
                "existed": true,
                "flow_control": "Auto",
                "gateway_address": "0.0.0.0",
                "hash": 6357823367617066385,
                "host_window": "256K",
                "initiator_authentication": "false",
                "ip_address": "172.19.1.2",
                "iscsi_alias": "357.a13",
                "port_id": 13,
                "port_speed": "10000 Mb",
                "replication_window": "256K",
                "sp": "VNXSPEnum.SP_A",
                "subnet_mask": "255.255.255.0",
                "type": "VNXPortType.ISCSI",
                "virtual_port_id": 0,
                "vlan_id": 506,
                "wwn": "iqn.1992-04.com.emc:cx.ckm00162000357.a13"
            }
        },
        {
            "VNXConnectionPort": {
                "auto_negotiate": false,
                "current_mtu": 9000,
                "enode_mac_address": "00-60-16-7A-15-AF",
                "existed": true,
                "flow_control": "Auto",
                "gateway_address": "0.0.0.0",
                "hash": 2040113515895134044,
                "host_window": "256K",
                "initiator_authentication": "false",
                "ip_address": "172.19.1.8",
                "iscsi_alias": "357.b13",
                "port_id": 13,
                "port_speed": "10000 Mb",
                "replication_window": "256K",
                "sp": "VNXSPEnum.SP_B",
                "subnet_mask": "255.255.255.0",
                "type": "VNXPortType.ISCSI",
                "virtual_port_id": 0,
                "vlan_id": 506,
                "wwn": "iqn.1992-04.com.emc:cx.ckm00162000357.b13"
            }
        }
    ]
}

Didnt find (yet.. ) where in the code is the issue ...

**Comment by peter-wangxu** [comment]
@yossiovadia 
We are fixing the issue in GH-169. Can you give a try for the fix in branch `fix_virtual_port`
Look forward to your feedback.

Thanks
Peter

**Comment by yossiovadia** [comment]
Progress !
I was able to create volume now, however, was not able to attach it to VM.

I only changed the files on the controllers ( not the computes ) i hope that's the issue: ( changing now.. will update )

2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager [req-6a8b4a2d-ccc1-4011-970d-6a0377c71906 d599e3a44889417a9ef1c35ae66e2124 19704c1384b44092ba44ced60fe23da1 - default default] Driver initialize connection failed (error: Bad
or unexpected response from the storage volume backend API: Failed to find available iSCSI targets for overcloud-triplenicovscompute-2.localdomain.).
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager Traceback (most recent call last):
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/manager.py", line 1429, in initialize_connection
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager     conn_info = self.driver.initialize_connection(volume, connector)
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/zonemanager/utils.py", line 81, in decorator
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager     conn_info = initialize_connection(self, *args, **kwargs)
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vnx/driver.py", line 197, in initialize_connection
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager     connector)
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vnx/adapter.py", line 906, in initialize_connection
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager     return self._initialize_connection(volume, connector)
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vnx/adapter.py", line 919, in _initialize_connection
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager     return self.prepare_target_data(sg, host, volume, hlu)
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vnx/adapter.py", line 1326, in prepare_target_data
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager     raise exception.VolumeBackendAPIException(data=msg)
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Failed to find available iSCSI targets for overcloud-triplenicovscompute-2.localdoma
in.
2017-10-20 01:34:43.508 29680 ERROR cinder.volume.manager
2017-10-20 01:34:43.512 29680 ERROR oslo_messaging.rpc.server [req-6a8b4a2d-ccc1-4011-970d-6a0377c71906 d599e3a44889417a9ef1c35ae66e2124 19704c1384b44092ba44ced60fe23da1 - default default] Exception during message handling
2017-10-20 01:34:43.512 29680 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
2017-10-20 01:34:43.512 29680 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 133, in _process_incoming
2017-10-20 01:34:43.512 29680 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
2017-10-20 01:34:43.512 29680 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 150, in dispatch
2017-10-20 01:34:43.512 29680 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
2017-10-20 01:34:43.512 29680 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 121, in _do_dispatch
2017-10-20 01:34:43.512 29680 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
2017-10-20 01:34:43.512 29680 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/manager.py", line 4403, in initialize_connection
2017-10-20 01:34:43.512 29680 ERROR oslo_messaging.rpc.server     connector, volume=volume)
2017-10-20 01:34:43.512 29680 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/manager.py", line 1437, in initialize_connection
2017-10-20 01:34:43.512 29680 ERROR oslo_messaging.rpc.server     raise exception.VolumeBackendAPIException(data=err_msg)
2017-10-20 01:34:43.512 29680 ERROR oslo_messaging.rpc.server VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Driver initialize connection failed (error: Bad or unexpected response from the

**Comment by peter-wangxu** [comment]
Let me try in openstack first.

**Comment by peter-wangxu** [comment]
Can you restart the cinder-volume and give a try?

Please also attach the cinder logs

Thanks
Peter

**Comment by yossiovadia** [comment]
Hooah!


yos | - | 1GiB | In-use | tripleo-emc | Attached to kkkk on /dev/vdc

**Comment by yossiovadia** [comment]
( restart cinder-volume did the trick ! )

Thanks!

**Comment by peter-wangxu** [comment]
Great, thanks for the feedback.

**Comment by peter-wangxu** [comment]
Closing it as fixed in release v0.5.4
