### ISSUE TITLE
VNX get_capacity exception

### ISSUE THREAD

**Issue by jasonchamiak** [emc-openstack/storops#176]
We have 63 VNX arrays that we are running storops against and one of the arrays is failing with the following error. I'm able to pull system information such as name, serial number, model, etc. without issue. Have you seen this before?

No handlers could be found for logger "storops.lib.converter"
Traceback (most recent call last):
  File "emc_capacity.py", line 71, in <module>
    capacity = json.loads(str(device.get_capacity()))
  File "/usr/lib/python2.7/site-packages/storops/lib/common.py", line 57, in __str__
    return self.json()
  File "/usr/lib/python2.7/site-packages/storops/lib/common.py", line 51, in json
    return json.dumps(self.get_dict_repr(), indent=indent, sort_keys=True)
  File "/usr/lib/python2.7/site-packages/storops/lib/common.py", line 46, in get_dict_repr
    props = self._get_properties(dec)
  File "/usr/lib/python2.7/site-packages/storops/vnx/resource/capacity.py", line 106, in _get_properties
    re[props] = getattr(self, props)
  File "/usr/lib/python2.7/site-packages/storops/lib/common.py", line 475, in _inner
    value = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/storops/vnx/resource/capacity.py", line 82, in used
    return self.total - self.free_storage_pool - self.free_raw_disk
  File "/usr/lib/python2.7/site-packages/storops/lib/common.py", line 475, in _inner
    value = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/storops/vnx/resource/capacity.py", line 72, in free_storage_pool
    self._update_free_pool_capacity()
  File "/usr/lib/python2.7/site-packages/storops/vnx/resource/capacity.py", line 99, in _update_free_pool_capacity
    free_in_rg = sum([rg.available_capacity_gbs for rg in rgs
  File "/usr/lib/python2.7/site-packages/storops/lib/resource.py", line 280, in __iter__
    return iter(self.list)
  File "/usr/lib/python2.7/site-packages/storops/lib/resource.py", line 261, in list
    self.update()
  File "/usr/lib/python2.7/site-packages/cachez.py", line 206, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/storops/vnx/resource/__init__.py", line 211, in update
    ret = super(VNXCliResourceList, self).update(data)
  File "/usr/lib/python2.7/site-packages/cachez.py", line 206, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/storops/vnx/resource/__init__.py", line 105, in update
    ret = super(VNXCliResource, self).update(data)
  File "/usr/lib/python2.7/site-packages/cachez.py", line 206, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/storops/lib/resource.py", line 232, in update
    parsed_list = self._parse_raw(data)
  File "/usr/lib/python2.7/site-packages/storops/lib/resource.py", line 252, in _parse_raw
    return self._get_parser().parse_all(data)
  File "/usr/lib/python2.7/site-packages/storops/vnx/parsers.py", line 125, in parse_all
    instances = self._parse_split_output(split_outputs, properties)
  File "/usr/lib/python2.7/site-packages/storops/vnx/parsers.py", line 157, in _parse_split_output
    parsed = self.parse_single(instance, properties)
  File "/usr/lib/python2.7/site-packages/storops/vnx/parsers.py", line 110, in parse_single
    value = p.convert(value)
  File "/usr/lib/python2.7/site-packages/storops/lib/parser.py", line 126, in convert
    ret = c(value)
  File "/usr/lib/python2.7/site-packages/storops/lib/converter.py", line 208, in _enum_converter
    return enum_class.parse(value)
  File "/usr/lib/python2.7/site-packages/storops/lib/common.py", line 136, in parse
    ret = cls.from_str(value)
  File "/usr/lib/python2.7/site-packages/storops/lib/common.py", line 187, in from_str
    cls._raise_invalid_value(value)
  File "/usr/lib/python2.7/site-packages/storops/lib/common.py", line 194, in _raise_invalid_value
    raise storops.exception.EnumValueNotFoundError(msg)
storops.exception.EnumValueNotFoundError: Unbound is not a valid value for VNXRaidType.

**Comment by yong-huang** [comment]
Could you provide the version of these VNX?

**Comment by jasonchamiak** [comment]
This is a 5300 running 05.32.000.5.219.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yong-huang** [comment]
It can be reproduced in my environment.

What is the raid type of the storage pools?

Could you mind showing the output of these naviseccli commands:
naviseccli.exe -h [ip] -user [user] -password [password] -scope 0 getdisk
naviseccli.exe -h [ip] -user [user] -password [password] -scope 0 storagepool -list -all
naviseccli.exe -h [ip] -user [user] -password [password] -scope 0 getrg

**Comment by jasonchamiak** [comment]
[SAN-getdisk.log](https://github.com/emc-openstack/storops/files/1506039/SAN-getdisk.log)
[SAN-getrg.log](https://github.com/emc-openstack/storops/files/1506040/SAN-getrg.log)
[SAN-storagepool.log](https://github.com/emc-openstack/storops/files/1506041/SAN-storagepool.log)

**Comment by yong-huang** [comment]
Could you try adding "UNBOUND = 'Unbound'" into "storops/vnx/enums.py" line#264, and rerun your script? If no issue, we will make a patch to fix it officially.

**Comment by jasonchamiak** [comment]
That worked. I'm now getting capacity data. Thanks so much.

**Comment by yong-huang** [comment]
Version 0.5.6 is released to fix this issue, thanks for the reporting and feedback.
I will close this ticket.
