### ISSUE TITLE
When compiled with pyinstaller can't read parser_configs.yaml

### ISSUE THREAD

**Issue by bonkeydcow** [emc-openstack/storops#278]
`UnitySystem.get_dict_repr()`

When I run this with python it runs, but if I compile to .exe with pyinstaller (on windows, haven't tested other OSes) I get the following error:

Traceback (most recent call last):
  File "unity.py", line 229, in <module>
  File "unity.py", line 170, in main
  File "Collect.py", line 211, in collect
  File "site-packages\storops\lib\common.py", line 46, in get_dict_repr
  File "site-packages\storops\unity\resource\__init__.py", line 125, in _get_properties
  File "site-packages\storops\lib\resource.py", line 143, in _get_properties
  File "site-packages\storops\unity\resource\__init__.py", line 149, in property_names
  File "site-packages\storops\lib\resource.py", line 118, in property_names
  File "site-packages\storops\unity\resource\__init__.py", line 43, in _get_parser
  File "site-packages\cachez.py", line 127, in func_wrapper
  File "site-packages\cachez.py", line 108, in _get_value_from_cache
  File "site-packages\storops\unity\parser.py", line 45, in get_unity_parser
  File "site-packages\storops\lib\parser.py", line 331, in get
  File "site-packages\storops\lib\parser.py", line 351, in get_config
  File "site-packages\storops\lib\parser.py", line 359, in _read_configs
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxx\\AppData\\Local\\Temp\\_MEI98002\\storops\\unity\\parser_configs.yaml'
[13560] Failed to execute script unity

**Comment by DingDino** [comment]
Hi, @bonkeydcow 

Looks like there are some same issues raised by other users for pyinstaller.
The thing is that we use relative path of config file in storops, but when execute the .exe file, it will create a temp folder but without the config file.
**Suggestions:**
1. Find below code of relative path in storops code('storops/lib/parser.py'  and 'storops/lib/metric.py'.)

filename = os.path.join(cls.get_folder(), cls.config_filename)

2. Change both of them to your local absolute storops code path like: 

filename = 'C:\\Test_folder\\storops\\storops\\unity\\parser_configs.yaml'

3. Recreate the .exe file using pyinstaller. 
    Then run it again.
